               WELCOME AUTHORIZED USER TO FTP SERVER!
 
WARNING!
This is a U.S. General Services Administration Federal government
computer system that is "FOR OFFICIAL USE ONLY". This system is subject
to monitoring. Therefore, no expectation of privacy is to be assumed.
Individuals found performing unauthorized activities are subject to
disciplinary action including criminal prosecution. 
 
            Have a reliable session!
                       
SysAdmin
